### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by yfzm** [yfzm/FPSEI-group2#35]
**12.21日（周四） 23:59:59**前需完成：

- [x] 完善数据文件，（书的数目至少30+）（包括加入二手书数据）

- [x] 完善搜索算法，处理空值、大小写等问题

- [x] 完善排序算法，处理空数据情形，显示无搜索结果

- [x] GoodList.vue页面展示更多信息，如商品来源（最好用图标）、卖家承诺等

- [x] 详情页整理排版，处理空数据情形

- [x] 各个组件中添加对二手书的支持

- [x] 加入footer.vue组件

- [x] 处理分页问题

- [x] 给我们的项目起个名字
